# Generated by Django 3.2.5 on 2022-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=200, verbose_name='username'),
            preserve_default=False,
        ),
    ]
