# Generated by Django 4.1.3 on 2022-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0003_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "host",
                    models.CharField(
                        default="smtp.gmail.com",
                        help_text='default host is "smtp.gmail.com". if you want to change it then give your host, otherwise leave it ',
                        max_length=50,
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        default=587,
                        help_text='default port is "587". if you want to change it then give your port no, otherwise leave it',
                    ),
                ),
                ("tls", models.BooleanField(default=False)),
                ("ssl", models.BooleanField(default=False)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    models.CharField(
                        help_text='<p><b>For Gmail: You need to follow those steps:</b></p><br><p>1. Enable 2-Step Verification from your gmail account.</p> <br><p>2. Generate an App passwords from your gmail account and upload here. <a href-"https://myaccount.google.com/apppasswords">Click here to go google settings.</a></p> <br>',
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
